# Generated by Django 5.1.6 on 2025-03-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_events_delete_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='events',
            new_name='participants',
        ),
    ]
