# Generated by Django 5.1.6 on 2025-03-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_events_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
