# Generated by Django 5.1.6 on 2025-03-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='events_asset/empty-image.jpg', upload_to='events_asset'),
        ),
    ]
